/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Subnomicon",
  "tagline": "Subnomicon is the source of knowledge about the Subspace Network scalable blockchain protocol",
  "url": "https://subnomicon.subspace.network",
  "baseUrl": "/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/favicon.ico",
  "organizationName": "subspace",
  "projectName": "subnomicon",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "plugins": [
    [
      "@docusaurus/plugin-google-gtag",
      {
        "trackingID": "G-25NWNJB9MR",
        "anonymizeIP": false
      }
    ]
  ],
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/Users/dariiap/Documents/GitHub/subspace/subnomicon/sidebars.js",
          "remarkPlugins": [
            null
          ],
          "rehypePlugins": [
            null
          ]
        },
        "blog": {
          "showReadingTime": true
        },
        "theme": {
          "customCss": "/Users/dariiap/Documents/GitHub/subspace/subnomicon/src/css/custom.css"
        },
        "sitemap": {
          "changefreq": "weekly",
          "priority": 0.5
        }
      }
    ]
  ],
  "stylesheets": [
    {
      "href": "https://cdn.jsdelivr.net/npm/katex@0.13.24/dist/katex.min.css",
      "type": "text/css",
      "integrity": "sha384-odtC+0UGzzFL/6PNoE8rX/SPcQDXBJ+uRepguP4QkPCm2LBxH3FA3y+fKSiJ+AmM",
      "crossorigin": "anonymous"
    }
  ],
  "themeConfig": {
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "navbar": {
      "title": "Subspace",
      "logo": {
        "alt": "Subspace Labs Logo",
        "src": "img/logo-black.svg",
        "srcDark": "img/logo-white.svg"
      },
      "items": [
        {
          "type": "doc",
          "docId": "intro",
          "position": "left",
          "label": "Subnomicon"
        },
        {
          "type": "dropdown",
          "label": "Network Resources",
          "position": "left",
          "items": [
            {
              "label": "Subspace Telemetry",
              "href": "https://telemetry.subspace.network"
            },
            {
              "label": "Subspace Explorer",
              "href": "https://subspace.subscan.io/"
            },
            {
              "label": "PolkadotJS Portal",
              "href": "https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Feu-1.gemini-2a.subspace.network%2Fws#/explorer"
            }
          ]
        },
        {
          "href": "https://docs.subspace.network",
          "label": "Farming",
          "position": "right"
        },
        {
          "href": "https://github.com/subspace",
          "label": "GitHub",
          "position": "right"
        },
        {
          "type": "localeDropdown",
          "position": "right",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Subspace Network",
          "items": [
            {
              "label": "Official Website",
              "href": "https://subspace.network"
            },
            {
              "label": "Subspace Desktop",
              "href": "https://github.com/subspace/subspace-desktop"
            },
            {
              "label": "Subspace Explorer",
              "href": "https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Ftest-rpc.subspace.network#/explorer"
            },
            {
              "label": "Subspace Relayer",
              "href": "https://testnet-relayer.subspace.network/"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/subspace"
            },
            {
              "label": "Discord",
              "href": "https://discord.gg/subspace-network"
            },
            {
              "label": "Telegram",
              "href": "https://t.me/subspace_network"
            },
            {
              "label": "Reddit",
              "href": "https://reddit.com/r/sub"
            }
          ]
        },
        {
          "title": "Social",
          "items": [
            {
              "label": "YouTube",
              "href": "https://www.youtube.com/channel/UCojYRCZOtVTJHJXivOYJzeQ"
            },
            {
              "label": "LinkedIn",
              "href": "https://www.linkedin.com/company/subspace-blockchain"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/network_subspace"
            },
            {
              "label": "Medium",
              "href": "https://medium.com/subspace-network"
            },
            {
              "label": "Subsocial",
              "href": "https://app.subsocial.network/@NetworkSubspace"
            }
          ]
        }
      ],
      "logo": {
        "alt": "Subspace Labs Banner Logo",
        "src": "img/banner-black.svg",
        "srcDark": "img/banner-white.svg",
        "href": "https://subspace.network"
      },
      "copyright": "Copyright © 2023 Subspace Labs, Inc."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "toml"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "headTags": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
